# Generated by Django 6.1.1 on 2026-09-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('start_lat__isnull', True), ('start_lat__range', (-90, 90)), _connector='OR'), name='course_start_lat_bounds'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('start_lng__isnull', True), ('start_lng__range', (-180, 180)), _connector='OR'), name='course_start_lng_bounds'),
        ),
        migrations.AddConstraint(
            model_name='coursestop',
            constraint=models.CheckConstraint(condition=models.Q(('lat__range', (-90, 90))), name='course_stop_lat_bounds'),
        ),
        migrations.AddConstraint(
            model_name='coursestop',
            constraint=models.CheckConstraint(condition=models.Q(('lng__range', (-180, 180))), name='course_stop_lng_bounds'),
        ),
    ]
