# Generated by Django 6.1.1 on 2026-09-14 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContext',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'HOME_CONTEXT',
            },
        ),
        migrations.CreateModel(
            name='PostseasonStage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stage_code', models.TextField(unique=True)),
                ('stage_name', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('matchup_description', models.TextField()),
                ('status_tag', models.TextField()),
                ('collected_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'POSTSEASON_STAGE',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stadium_code', models.TextField(unique=True)),
                ('stadium_name_ko', models.TextField()),
                ('address', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('geocode_source', models.TextField()),
                ('facility_manager', models.TextField(blank=True, null=True)),
                ('game_operator', models.TextField(blank=True, null=True)),
                ('phone_general', models.TextField(blank=True, null=True)),
                ('phone_facility', models.TextField(blank=True, null=True)),
                ('phone_ticket', models.TextField(blank=True, null=True)),
                ('collected_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'STADIUM',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_code', models.TextField(unique=True)),
                ('team_name_ko', models.TextField()),
            ],
            options={
                'db_table': 'TEAM',
            },
        ),
        migrations.CreateModel(
            name='SeatMap',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('map_title', models.TextField()),
                ('page_url', models.TextField()),
                ('home_context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_maps', to='baseball.homecontext')),
            ],
            options={
                'db_table': 'SEAT_MAP',
            },
        ),
        migrations.CreateModel(
            name='SeatScope',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('scope_code', models.TextField()),
                ('scope_name', models.TextField()),
                ('home_context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_scopes', to='baseball.homecontext')),
            ],
            options={
                'db_table': 'SEAT_SCOPE',
            },
        ),
        migrations.CreateModel(
            name='SeatView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('view_characteristic', models.TextField()),
                ('roof_coverage', models.TextField()),
                ('evidence_scope', models.TextField()),
                ('seat_scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_views', to='baseball.seatscope')),
            ],
            options={
                'db_table': 'SEAT_VIEW',
            },
        ),
        migrations.CreateModel(
            name='SeatZone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('zone_code', models.TextField()),
                ('zone_name_ko', models.TextField()),
                ('level', models.TextField()),
                ('side', models.TextField()),
                ('seat_type', models.TextField()),
                ('group_size', models.IntegerField(blank=True, null=True)),
                ('accessible', models.BooleanField(blank=True, null=True)),
                ('home_context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_zones', to='baseball.homecontext')),
            ],
            options={
                'db_table': 'SEAT_ZONE',
            },
        ),
        migrations.AddField(
            model_name='homecontext',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_contexts', to='baseball.stadium'),
        ),
        migrations.CreateModel(
            name='FoodStore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('record_code', models.TextField(unique=True)),
                ('store_facility', models.TextField()),
                ('location_qty', models.IntegerField(blank=True, null=True)),
                ('collected_at', models.DateTimeField()),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_stores', to='baseball.stadium')),
            ],
            options={
                'db_table': 'FOOD_STORE',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('record_code', models.TextField(unique=True)),
                ('facility_type', models.TextField()),
                ('floor', models.TextField()),
                ('side', models.TextField()),
                ('nearby_section', models.TextField()),
                ('gate', models.TextField()),
                ('gender', models.TextField()),
                ('indoor_outdoor', models.TextField()),
                ('location_detail', models.TextField()),
                ('collected_at', models.DateTimeField()),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='baseball.stadium')),
            ],
            options={
                'db_table': 'FACILITY',
            },
        ),
        migrations.CreateModel(
            name='StadiumContent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('record_code', models.TextField(unique=True)),
                ('content_type', models.TextField()),
                ('name', models.TextField()),
                ('floor', models.TextField()),
                ('location', models.TextField()),
                ('official_description', models.TextField()),
                ('operating_condition', models.TextField()),
                ('collected_at', models.DateTimeField()),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='baseball.stadium')),
            ],
            options={
                'db_table': 'STADIUM_CONTENT',
            },
        ),
        migrations.CreateModel(
            name='StandingHistory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('rank', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('games_behind', models.DecimalField(decimal_places=2, max_digits=8)),
                ('collected_at', models.DateTimeField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standing_histories', to='baseball.team')),
            ],
            options={
                'db_table': 'STANDING_HISTORY',
            },
        ),
        migrations.AddField(
            model_name='homecontext',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_contexts', to='baseball.team'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_code', models.TextField(unique=True)),
                ('game_date', models.DateField()),
                ('game_time', models.TimeField()),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('status_code', models.TextField()),
                ('game_type', models.TextField()),
                ('collected_at', models.DateTimeField()),
                ('postseason_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='baseball.postseasonstage')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='baseball.stadium')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='baseball.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='baseball.team')),
            ],
            options={
                'db_table': 'GAME',
            },
        ),
        migrations.CreateModel(
            name='TicketPolicy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('policy_code', models.TextField()),
                ('policy_type', models.TextField()),
                ('subtype', models.TextField()),
                ('open_at', models.DateTimeField(blank=True, null=True)),
                ('max_tickets', models.IntegerField(blank=True, null=True)),
                ('channel_no', models.IntegerField()),
                ('booking_channel', models.TextField()),
                ('channel_condition', models.TextField()),
                ('collected_at', models.DateTimeField()),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_policies', to='baseball.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_policies', to='baseball.team')),
            ],
            options={
                'db_table': 'TICKET_POLICY',
            },
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price_tier', models.TextField()),
                ('day_type', models.TextField()),
                ('customer_type', models.TextField()),
                ('group_size', models.IntegerField(blank=True, null=True)),
                ('price_krw', models.IntegerField()),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('discount_condition', models.TextField()),
                ('collected_at', models.DateTimeField()),
                ('seat_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_prices', to='baseball.seatzone')),
            ],
            options={
                'db_table': 'TICKET_PRICE',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('access_code', models.TextField()),
                ('mode', models.TextField()),
                ('title', models.TextField()),
                ('details', models.TextField()),
                ('parking_spaces', models.IntegerField(blank=True, null=True)),
                ('reservation_required', models.BooleanField(blank=True, null=True)),
                ('collected_at', models.DateTimeField()),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transports', to='baseball.stadium')),
            ],
            options={
                'db_table': 'TRANSPORT',
            },
        ),
        migrations.CreateModel(
            name='FoodStoreLocation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location_no', models.IntegerField()),
                ('floor', models.TextField()),
                ('zone_location', models.TextField()),
                ('food_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='baseball.foodstore')),
            ],
            options={
                'db_table': 'FOOD_STORE_LOCATION',
                'constraints': [models.UniqueConstraint(fields=('food_store', 'location_no'), name='uq_food_store_location_no')],
            },
        ),
        migrations.CreateModel(
            name='FoodStoreMenu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('menu_category_official', models.TextField()),
                ('food_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='baseball.foodstore')),
            ],
            options={
                'db_table': 'FOOD_STORE_MENU',
                'constraints': [models.UniqueConstraint(fields=('food_store', 'menu_category_official'), name='uq_food_store_menu_category')],
            },
        ),
        migrations.CreateModel(
            name='SeatMapAsset',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('asset_no', models.IntegerField()),
                ('asset_url', models.TextField()),
                ('asset_role', models.TextField()),
                ('seat_map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='baseball.seatmap')),
            ],
            options={
                'db_table': 'SEAT_MAP_ASSET',
                'constraints': [models.UniqueConstraint(fields=('seat_map', 'asset_no'), name='uq_seat_map_asset_no')],
            },
        ),
        migrations.AddConstraint(
            model_name='seatscope',
            constraint=models.UniqueConstraint(fields=('home_context', 'scope_code'), name='uq_seat_scope_context_code'),
        ),
        migrations.AddConstraint(
            model_name='seatzone',
            constraint=models.UniqueConstraint(fields=('home_context', 'zone_code'), name='uq_seat_zone_context_code'),
        ),
        migrations.AddConstraint(
            model_name='standinghistory',
            constraint=models.UniqueConstraint(fields=('team', 'snapshot_date'), name='uq_standing_team_date'),
        ),
        migrations.AddConstraint(
            model_name='homecontext',
            constraint=models.UniqueConstraint(fields=('season', 'team', 'stadium'), name='uq_home_context'),
        ),
        migrations.AddConstraint(
            model_name='ticketpolicy',
            constraint=models.UniqueConstraint(fields=('policy_code', 'channel_no'), name='uq_ticket_policy_channel'),
        ),
        migrations.AddConstraint(
            model_name='transport',
            constraint=models.UniqueConstraint(fields=('stadium', 'access_code'), name='uq_transport_stadium_access'),
        ),
    ]
