# Generated by Django 6.1.1 on 2026-09-15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("llm", "0003_chatmessage_role")]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("completed", "완료"), ("stopped", "중단")],
                default="",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ChatTurn",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("base_sequence", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("pending", "대기"), ("completed", "완료"), ("stopped", "중단")], default="pending", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assistant_message", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="llm.chatmessage")),
                ("human_message", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="llm.chatmessage")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="turns", to="llm.chatsession")),
            ],
        ),
    ]
